name: Run tests in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker build -t uptime-monitor-test .

      - name: Run tests inside Docker
        run: docker run --rm uptime-monitor-test pytest